### ISSUE TITLE
Unknown errors when deleting studies from devtree curation

### ISSUE THREAD

**Issue by jimallman** [OpenTreeOfLife/phylesystem-api#140]
I've tried deleting several studies (in UI testing), from the curation tool in both my local test server and **devtree**. In all cases, it fails without explanation.
```json
{"description": "Unknown error in study deletion", "error": 1}
```
I haven't changed the delete request lately, so I'm not sure what's going wrong. Perhaps this has been around for awhile, but it's not been reported since deletion is rare?

**Comment by mtholder** [comment]
thanks for reporting this. I'll try to look at it tomorrow. on a quick test - I don't have a problem with my local version, but can reproduce this on devtree. I'm having one other issue on my local deployment. So, I'll try a clean install in another part of my fs to see if I can figure out why we're out of sync.
There is a possibility that redeploying on devtree will fix this, but I'd like to understand the cause of the error before I do that.

**Comment by mtholder** [comment]
just a note that 
   https://github.com/OpenTreeOfLife/phylesystem-api/blob/master/controllers/default.py#L808
indicates that the exception is getting logged. So, dredging through those logs is probably a good place to start.

**Comment by mtholder** [comment]
@snacktavish and I have looked at this. It think this is the result of a version of phylesystem-api from https://github.com/OpenTreeOfLife/phylesystem-api/tree/comment-on-delete-study
being deployed on devapi, but not a corresponding version of peyotl.
It looks like we are passing in an incorrect # of args. I think that if we merge that api branch and https://github.com/OpenTreeOfLife/peyotl/tree/comment-on-delete-study
then we'll be OK (or if we make sure to deploy them in sync).

PS: it is kind of hard to tell what is safe to deploy on dev. we might want to prioritize getting the small (one-per-developer) testing instances working. I can't remember if there is an issue for that. @jar398  do you know?

**Comment by jimallman** [comment]
> We think this is the result of a version of phylesystem-api from https://github.com/OpenTreeOfLife/phylesystem-api/tree/comment-on-delete-study
being deployed on devapi, but not a corresponding version of peyotl.

That makes sense. But I thought you needed to do more work on the peyotl branch to complete this, right? [See related discussion here.](https://github.com/OpenTreeOfLife/opentree/issues/486) I don't see anything more recent in [peyotl's commit history](https://github.com/OpenTreeOfLife/peyotl/commits/comment-on-delete-study). 

Alternately, we can switch phylesystem-api back to `master` branch.

**Comment by mtholder** [comment]
ah, yes. sorry I forgot about that. i'll try to catch up this weekend or early next week.

**Comment by snacktavish** [comment]
This is all sorted now, right?
