### ISSUE TITLE
Lag btw submitting study & having in API

### ISSUE THREAD

**Issue by bomeara** [OpenTreeOfLife/phylesystem-api#154]
Submitted https://tree.opentreeoflife.org/curator/study/view/ot_308 a couple of days ago, but it doesn't seem to be showing up in the API pull (using CRAN package rotl). I'm not sure if this is expected behavior (weekly rebuild of the index of files or something like that). DateLife is moving from its own ad hoc treestore to OpenTree's, and I'd like to know how often to pull trees via the api for a local cache.

**Comment by jar398** [comment]
This seems to be a bug with the open tree store; changes to a study are
supposed to lead to more or less immediate re-indexing. I'll look into it.
Thanks for your patience.

Jonathan

**Comment by mtholder** [comment]
curl -X POST http://api.opentreeoflife.org/v2/studies/find_studies -H "content-type:application/json" -d '{"property":"ot:studyId","value":"ot_308","verbose":true}'

finds the study, @bomeara can you provide some details of what methods you are using in rotl? I have not looked at that CRAN package.

**Comment by jimallman** [comment]
FYI - this study is also showing up in the main curation UI (but perhaps someone has nudged the index): 
https://tree.opentreeoflife.org/curator/?match=delayed+rise+of+present-day+mammals

**Comment by mtholder** [comment]
FWIW: I haven't nudged it via any command line action or call to the web services. I think that it gets nudges whenever that study is saved, but that was not today.

**Comment by jar398** [comment]
right, I haven't done anything with the study index today either, I'm
working on something else.

**Comment by bomeara** [comment]
Was doing, in rotl: studies_find_trees(property="ot:branchLengthMode", value="ot:time")[[1]] 

Now it does find that study. Something Joseph Brown pointed out on twitter: I hadn't specified ingroup node; changed that, and now the study is found using the call above. It had been showing up in the UI the whole time, but not the rotl call. So perhaps it was re-indexed, or perhaps it just wasn't complete enough until I updated the ingroup node?

**Comment by bomeara** [comment]
Given that the issue may have been my user error (not specifying the ingroup node) I'm marking this closed, though of course reopen if you think it points to something else.
