### ISSUE TITLE
Status 200 where 404 is required

### ISSUE THREAD

**Issue by jar398** [OpenTreeOfLife/phylesystem-api#182]
E.g.
https://devapi.opentreeoflife.org/phylesystem/v1/study/pg_90/file/bogusid
Payload is "404 NOT FOUND" but response code is 200

**Comment by jimallman** [comment]
This shows up when running phylesystem-api unit tests.

**Comment by jar398** [comment]
You see this as an error in running ws-tests only if either (a) you turn on debugging output, or (b) you use the version of opentreetesting.py in the germinator repo instead of the one in the phylesystem-api repo.  The germinator version of the harness fixes a bug in the phylesystem-api version of the harness - the failure in the test was being detected but not reported as a failure.

**Comment by mtholder** [comment]
https://github.com/OpenTreeOfLife/phylesystem-api/pull/196/commits/497d6593f5dbb0a38a2371112468d37dd437d8ae
