### ISSUE TITLE
OTU change should not jump to first page of OTU list

### ISSUE THREAD

**Issue by Artoria2e5** [OpenTreeOfLife/phylesystem-api#229]
I am trying to curate a [pretty large and messy dataset](https://tree.opentreeoflife.org/curator/study/edit/ot_2006) from GTDB. If I try to match OTUs on page 2 of the OTU list (by using a name-based sort order), the candidates show up normally, but every time I click to confirm or reject one, the whole thing jumps back to page 1. I have to scroll down the page to get to page 2 to click the next one, and that's... very frustrating.

**Comment by Artoria2e5** [comment]
A related issue is that the OTU match does not really work on page 2/3/4... when the sort order is "unmapped first". The page seems to find some matches, decides to jump to page 1, and stops matching because nothing else is selected on this page. I feel this is the same issue, so I am not opening a separate one.

**Comment by mtholder** [comment]
thanks for the report. Sorry that it was frustrating.
We do know that is difficult for data sets beyond a few hundred tips. We started working on an alternative method of getting trees into the synthesis other than curator app. In fact, we were thinking about the GTDB tree as a motivating example. We have a very old version of a GTDB tree at https://github.com/OpenTreeOfLife/script-managed-trees
I can move your work from https://tree.opentreeoflife.org/curator/study/view/ot_2006 there, perhaps. I can look at it next week.

**Comment by jimallman** [comment]
> If I try to match OTUs on page 2 of the OTU list (by using a name-based sort order), the candidates show up normally, but every time I click to confirm or reject one, the whole thing jumps back to page 1.

Just to clarify, the behavior is the same regardless of sort order -- unwanted bounce to page 1.

**Comment by Artoria2e5** [comment]
Hey uh, I think it's fixed so I can close it? I am taking a loooong break from any computer stuff right now, so I am afraid that the GTDB import is not going to happen anytime soon. Sorry.
