### ISSUE TITLE
Feature request: Import/export for OTU mapping

### ISSUE THREAD

**Issue by Artoria2e5** [OpenTreeOfLife/phylesystem-api#230]
Following my frustration with the OTU editing thing, may I ask for an import/export functionality for the OTU mapping of studies? I expect a TSV format where the three columns are the original (in-tree) name, the candidate mapping name, and the OTT taxonomy id number.

I feel that I might be able to do it faster off-line with an OTT dump.

**Comment by Artoria2e5** [comment]
Oops, I thought I was in the opentree repo! Can both of my issues be transferred?

**Comment by jimallman** [comment]
Hi, @Artoria2e5. I'm making a new issue in our feedback repository that points to these. (I'm a web-app developer for the Open Tree project.) Our [bulk TNRS tool](https://tree.opentreeoflife.org/curator/tnrs/) might work better for your situation, though it shares a lot of the same client-side code with the OTU mapping tool in the study editor.

**Comment by Artoria2e5** [comment]
Gonna close the issue now that a proper one has been created. Don't wanna clog the open list up :)
